### ISSUE TITLE
Problem with Intellij 15 RC

### ISSUE THREAD

**Issue by testn** [destin/maven-test-support-plugin#10]
```com.intellij.execution.testframework.ui.TestResultsPanel.<init>(Ljavax/swing/JComponent;[Lcom/intellij/openapi/actionSystem/AnAction;Lcom/intellij/execution/testframework/TestConsoleProperties;Lcom/intellij/execution/runners/ExecutionEnvironment;Ljava/lang/String;F)V
java.lang.NoSuchMethodError: com.intellij.execution.testframework.ui.TestResultsPanel.<init>(Ljavax/swing/JComponent;[Lcom/intellij/openapi/actionSystem/AnAction;Lcom/intellij/execution/testframework/TestConsoleProperties;Lcom/intellij/execution/runners/ExecutionEnvironment;Ljava/lang/String;F)V
	at org.dpytel.intellij.plugin.maventest.view.MavenTestResultsPanel.<init>(MavenTestResultsPanel.java:59)
	at org.dpytel.intellij.plugin.maventest.view.MavenTreeConsoleView.createTestResultsPanel(MavenTreeConsoleView.java:50)
	at com.intellij.execution.testframework.ui.BaseTestsOutputConsoleView.initUI(BaseTestsOutputConsoleView.java:55)
	at org.dpytel.intellij.plugin.maventest.view.MavenTreeConsoleView.initUI(MavenTreeConsoleView.java:56)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.attachModelToView(MavenToolWindow.java:82)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.createMavenTreeConsoleView(MavenToolWindow.java:77)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.showMavenToolWindow(MavenToolWindow.java:52)
	at org.dpytel.intellij.plugin.maventest.actions.ShowTestResultsAction.actionPerformed(ShowTestResultsAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:299)
	at java.awt.Component.processEvent(Component.java:6308)
	at java.awt.Container.processEvent(Container.java:2235)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2293)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
	at java.awt.Container.dispatchEventImpl(Container.java:2279)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```

**Comment by destin** [comment]
Thank you for raising this problem. Indeed IntelliJ junit API changed. I try to keep the plugin compatible with older IJ versions but it is getting even harder.

Hopefully by the end of next week I will be able to get the plugin working with IJ 15RC

**Comment by destin** [comment]
I fixed the problem but the plugin is no longer compatible with IntelliJ pre-15 versions. 

I don't guarantee that the plugin is compatible with IntelliJ 15 RC so I suggest using recently released version IJ 15 instead of release candidate.

The new plugin version should be available within 2 days.
