### ISSUE TITLE
Crash in IntelliJ 16 EAP

### ISSUE THREAD

**Issue by brcolow** [destin/maven-test-support-plugin#11]
I know you don't claim compatbility with 16 EAP (which was just released very recently), but just as a potential heads up, I am experience the following error when trying to "Show Test Results":

````
Sorry but parent: com.intellij.execution.junit2.ui.model.JUnitRunningModel@48a2b6 has already been disposed (see the cause for stacktrace) so the child: net.cryptodirect.cryptodash:core:0.1-SNAPSHOT.core will never be disposed
com.intellij.util.IncorrectOperationException: Sorry but parent: com.intellij.execution.junit2.ui.model.JUnitRunningModel@48a2b6 has already been disposed (see the cause for stacktrace) so the child: net.cryptodirect.cryptodash:core:0.1-SNAPSHOT.core will never be disposed
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:66)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:92)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:86)
	at com.intellij.execution.testframework.TestTreeView.attachToModel(TestTreeView.java:79)
	at org.dpytel.intellij.plugin.maventest.view.MavenTreeConsoleView.initUI(MavenTreeConsoleView.java:59)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.attachModelToView(MavenToolWindow.java:82)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.createMavenTreeConsoleView(MavenToolWindow.java:77)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.showMavenToolWindow(MavenToolWindow.java:52)
	at org.dpytel.intellij.plugin.maventest.actions.ShowTestResultsAction.actionPerformed(ShowTestResultsAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:180)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
````

Cheers.

**Comment by destin** [comment]
Thanks for raising this issue. I will take a look at this this week.

**Comment by destin** [comment]
I sent plugin for update. In 2-3 days the new version should be available in Jetbrains plugin reop
