### ISSUE TITLE
IntelliJ IDEA 2017.1 - NoSuchMethodError

### ISSUE THREAD

**Issue by tibormucha** [destin/maven-test-support-plugin#14]
selecting "Show Test Results" cause exception after IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017

```
com.intellij.execution.testframework.sm.runner.events.TestFinishedEvent.<init>(Ljava/lang/String;Ljava/lang/String;J)V
java.lang.NoSuchMethodError: com.intellij.execution.testframework.sm.runner.events.TestFinishedEvent.<init>(Ljava/lang/String;Ljava/lang/String;J)V
	at org.dpytel.intellij.plugin.maventest.ReportParser.parseTestCase(ReportParser.java:85)
	at org.dpytel.intellij.plugin.maventest.ReportParser.parseTestSuite(ReportParser.java:59)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseAndAddToRoot(SurefireTestReportsParser.java:101)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.addReports(SurefireTestReportsParser.java:89)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.processReportsDir(SurefireTestReportsParser.java:81)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseReportFiles(SurefireTestReportsParser.java:71)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseReports(SurefireTestReportsParser.java:56)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenTestConsoleProperties$1.lambda$onStartTesting$0(MavenTestConsoleProperties.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by destin** [comment]
Thanks for letting me know. Seemingly JetBrains again tweaks the API for displaying test results :disappointed: 

I will take a look at it even today.

**Comment by arngrimur** [comment]
Can verify this bug, 
`com.intellij.execution.testframework.sm.runner.events.TestFinishedEvent.<init>(Ljava/lang/String;Ljava/lang/String;J)V
java.lang.NoSuchMethodError: com.intellij.execution.testframework.sm.runner.events.TestFinishedEvent.<init>(Ljava/lang/String;Ljava/lang/String;J)V
	at org.dpytel.intellij.plugin.maventest.ReportParser.parseTestCase(ReportParser.java:85)
	at org.dpytel.intellij.plugin.maventest.ReportParser.parseTestSuite(ReportParser.java:59)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseAndAddToRoot(SurefireTestReportsParser.java:101)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.addReports(SurefireTestReportsParser.java:89)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.processReportsDir(SurefireTestReportsParser.java:81)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseReportFiles(SurefireTestReportsParser.java:71)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseReports(SurefireTestReportsParser.java:56)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenTestConsoleProperties$1.lambda$onStartTesting$0(MavenTestConsoleProperties.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by destin** [comment]
Thank you both for raising this. I've just uploaded fixed version to JetBrains. Should be available for update soon.

**Comment by arngrimur** [comment]
Thanks for the good work and quick response. Very much appreciated!

**Comment by tibormucha** [comment]
@arngrimur you are welcome
@destin thx for fixing

tested, it works
