### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by HeilmannKarl** [destin/maven-test-support-plugin#20]
Dear Sir or Madam,
if i exceute your plugin in Intellij through right click on maven goal web -> ShowTestResultsAction I get the following Exception (i am using IntelliJ IDEA 2022.1.1 (Ultimate Edition)) :

java.lang.IllegalStateException: Unknown state: system-out
	at org.dpytel.intellij.plugin.maventest.ReportParser.parseTestCase(ReportParser.java:118)
	at org.dpytel.intellij.plugin.maventest.ReportParser.parseTestSuite(ReportParser.java:60)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseAndAddToRoot(SurefireTestReportsParser.java:101)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.addReports(SurefireTestReportsParser.java:89)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.processReportsDir(SurefireTestReportsParser.java:81)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseReportFiles(SurefireTestReportsParser.java:71)
	at org.dpytel.intellij.plugin.maventest.SurefireTestReportsParser.parseReports(SurefireTestReportsParser.java:56)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenTestConsoleProperties$1.lambda$onStartTesting$0(MavenTestConsoleProperties.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by PorkLip** [comment]
This probably the same issue as reported in #19

**Comment by foreverigor** [comment]
Hey guys, I found this plugin and decided to fix it myself https://github.com/foreverigor/maven-test-support-plugin/releases/tag/0.0.21-2024
