### ISSUE TITLE
IntelliJ IDEA 15 EAP not compatible

### ISSUE THREAD

**Issue by DavidZemon** [destin/maven-test-support-plugin#8]
Upon trying to open the the results tab, this exception occurs every time, without fail in the v15 EAP.

I'm quite anxious for you to get this fixed - I love the features introduced in EAP but I _also_ love the features of your plugin! Sad day that they don't play well together yet :(

```
null
java.lang.NullPointerException
	at org.dpytel.intellij.plugin.maventest.view.MavenToolbarPanel.setMyModel(MavenToolbarPanel.java:57)
	at org.dpytel.intellij.plugin.maventest.view.MavenToolbarPanel.<init>(MavenToolbarPanel.java:41)
	at org.dpytel.intellij.plugin.maventest.view.MavenTestResultsPanel.createToolbarPanel(MavenTestResultsPanel.java:82)
	at com.intellij.execution.testframework.ui.TestResultsPanel.initUI(TestResultsPanel.java:83)
	at org.dpytel.intellij.plugin.maventest.view.MavenTestResultsPanel.initUI(MavenTestResultsPanel.java:67)
	at com.intellij.execution.testframework.ui.BaseTestsOutputConsoleView.initUI(BaseTestsOutputConsoleView.java:56)
	at org.dpytel.intellij.plugin.maventest.view.MavenTreeConsoleView.initUI(MavenTreeConsoleView.java:57)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.attachModelToView(MavenToolWindow.java:81)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.createMavenTreeConsoleView(MavenToolWindow.java:76)
	at org.dpytel.intellij.plugin.maventest.toolwindow.MavenToolWindow.showMavenToolWindow(MavenToolWindow.java:52)
	at org.dpytel.intellij.plugin.maventest.actions.ShowTestResultsAction.actionPerformed(ShowTestResultsAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:299)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:653)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:392)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by destin** [comment]
Thanks for letting me know about this problem. Indeed, I have reproduced the issue. Looks like some API changed. I will try to fix it. I think in 2-3 days update of the plugin should be available.

**Comment by destin** [comment]
Ok, I managed to fix the problem. I sent update to jetbrains, in 1-2 days new version of the plugin should be available.

If you need it now you can download the new version manually:
https://github.com/destin/maven-test-support-plugin/releases/tag/maven-test-support-plugin-0.0.16
but in this case you will not get automatic updates.

Thanks again for notifying me and I am happy the plugin is useful for you. If you have any suggestions for improving it feel free to raise another issue.

**Comment by DavidZemon** [comment]
Cool! Good job on the quick fix :)
